[package]
name = "simple_led"
version = "0.1.0"
authors = ["pi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"